spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/subway;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
